// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Coinbase Pro API for .NET")]
[assembly: AssemblyProductAttribute("Coinbase.Pro")]
[assembly: AssemblyCompanyAttribute("Brian Chavez")]
[assembly: AssemblyCopyrightAttribute("Brian Chavez © 2018")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-localbuild built on 12/1/2018 10:41:39 PM")]
[assembly: AssemblyTrademarkAttribute("MIT License")]
[assembly: AssemblyDescriptionAttribute("https://github.com/bchavez/Coinbase.Pro")]
[assembly: InternalsVisibleToAttribute("Coinbase.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Coinbase Pro API for .NET";
        internal const System.String AssemblyProduct = "Coinbase.Pro";
        internal const System.String AssemblyCompany = "Brian Chavez";
        internal const System.String AssemblyCopyright = "Brian Chavez © 2018";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 12/1/2018 10:41:39 PM";
        internal const System.String AssemblyTrademark = "MIT License";
        internal const System.String AssemblyDescription = "https://github.com/bchavez/Coinbase.Pro";
        internal const System.String InternalsVisibleTo = "Coinbase.Tests";
    }
}
